package View;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

public class BuatBerkas extends javax.swing.JFrame {

    public BuatBerkas() {
        initComponents();
    }

    public JButton getBtnBuatBerkas() {
        return btnBuatBerkas;
    }

    public JToggleButton getBtnHalAwal() {
        return btnHalAwal;
    }

    public JTextField getNamaBerkas() {
        return namaBerkas;
    }

    public void setNamaBerkas(JTextField namaBerkas) {
        this.namaBerkas = namaBerkas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        namaBerkas = new javax.swing.JTextField();
        btnBuatBerkas = new javax.swing.JButton();
        btnHalAwal = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Nama Berkas");

        namaBerkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBerkasActionPerformed(evt);
            }
        });

        btnBuatBerkas.setText("Buat berkas");
        btnBuatBerkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatBerkasActionPerformed(evt);
            }
        });

        btnHalAwal.setText("Kembali Ke Halaman Awal ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHalAwal)
                    .addComponent(btnBuatBerkas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namaBerkas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHalAwal)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaBerkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnBuatBerkas)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaBerkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBerkasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBerkasActionPerformed

    private void btnBuatBerkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatBerkasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuatBerkasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuatBerkas;
    private javax.swing.JToggleButton btnHalAwal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField namaBerkas;
    // End of variables declaration//GEN-END:variables
}
