package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

public class HalAwalPelamar extends javax.swing.JFrame {

    public HalAwalPelamar() {
        initComponents();
    }

    public JButton getBtnBuatBerkas() {
        return btnBuatBerkas;
    }

    public JButton getBtnTambahPelamar() {
        return btnTambahPelamar;
    }
    
    public void addListener(ActionListener e){
        btnBuatBerkas.addActionListener(e);
        btnTambahPelamar.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambahPelamar = new javax.swing.JButton();
        btnBuatBerkas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Awal Pelamar");

        btnTambahPelamar.setText("Tambah Pelamar");
        btnTambahPelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPelamarActionPerformed(evt);
            }
        });

        btnBuatBerkas.setText("Buat Berkas");
        btnBuatBerkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatBerkasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambahPelamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuatBerkas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnTambahPelamar)
                .addGap(39, 39, 39)
                .addComponent(btnBuatBerkas)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPelamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahPelamarActionPerformed

    private void btnBuatBerkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatBerkasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuatBerkasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuatBerkas;
    private javax.swing.JButton btnTambahPelamar;
    // End of variables declaration//GEN-END:variables
}
