package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

public class TambahPelamar extends javax.swing.JFrame {

    public TambahPelamar() {
        initComponents();
    }

    public JButton getBackButtonMainMenu() {
        return backButtonMainMenu;
    }

    public JTextField getNamaPelamar() {
        return namaPelamar;
    }

    public JButton getTambahButton() {
        return tambahButton;
    }
    
    public void addListener(ActionListener e){
        backButtonMainMenu.addActionListener(e);
        tambahButton.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButtonMainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        namaPelamar = new javax.swing.JTextField();
        tambahButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButtonMainMenu.setText("Kembali Ke Main Menu");
        backButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonMainMenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Pelamar");

        tambahButton.setText("Tambah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButtonMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(namaPelamar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButtonMainMenu)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namaPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(tambahButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namaPelamar;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
